/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as AuthenticatedWaitingRoomRouteImport } from './routes/_authenticated/waiting-room'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedInsightsReceptionRouteImport } from './routes/_authenticated/insights.reception'
import { Route as AuthenticatedInsightsDoctorRouteImport } from './routes/_authenticated/insights.doctor'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitingRoomRoute =
  AuthenticatedWaitingRoomRouteImport.update({
    id: '/waiting-room',
    path: '/waiting-room',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsReceptionRoute =
  AuthenticatedInsightsReceptionRouteImport.update({
    id: '/insights/reception',
    path: '/insights/reception',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsDoctorRoute =
  AuthenticatedInsightsDoctorRouteImport.update({
    id: '/insights/doctor',
    path: '/insights/doctor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/track/$token': typeof TrackTokenRoute
  '/insights/doctor': typeof AuthenticatedInsightsDoctorRoute
  '/insights/reception': typeof AuthenticatedInsightsReceptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/track/$token': typeof TrackTokenRoute
  '/insights/doctor': typeof AuthenticatedInsightsDoctorRoute
  '/insights/reception': typeof AuthenticatedInsightsReceptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/_authenticated/waiting-room': typeof AuthenticatedWaitingRoomRoute
  '/track/$token': typeof TrackTokenRoute
  '/_authenticated/insights/doctor': typeof AuthenticatedInsightsDoctorRoute
  '/_authenticated/insights/reception': typeof AuthenticatedInsightsReceptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/doctor'
    | '/reception'
    | '/waiting-room'
    | '/track/$token'
    | '/insights/doctor'
    | '/insights/reception'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/doctor'
    | '/reception'
    | '/waiting-room'
    | '/track/$token'
    | '/insights/doctor'
    | '/insights/reception'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/demo'
    | '/_authenticated/doctor'
    | '/_authenticated/reception'
    | '/_authenticated/waiting-room'
    | '/track/$token'
    | '/_authenticated/insights/doctor'
    | '/_authenticated/insights/reception'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrackTokenRoute: typeof TrackTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiting-room': {
      id: '/_authenticated/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof AuthenticatedWaitingRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights/reception': {
      id: '/_authenticated/insights/reception'
      path: '/insights/reception'
      fullPath: '/insights/reception'
      preLoaderRoute: typeof AuthenticatedInsightsReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights/doctor': {
      id: '/_authenticated/insights/doctor'
      path: '/insights/doctor'
      fullPath: '/insights/doctor'
      preLoaderRoute: typeof AuthenticatedInsightsDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedWaitingRoomRoute: typeof AuthenticatedWaitingRoomRoute
  AuthenticatedInsightsDoctorRoute: typeof AuthenticatedInsightsDoctorRoute
  AuthenticatedInsightsReceptionRoute: typeof AuthenticatedInsightsReceptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedWaitingRoomRoute: AuthenticatedWaitingRoomRoute,
  AuthenticatedInsightsDoctorRoute: AuthenticatedInsightsDoctorRoute,
  AuthenticatedInsightsReceptionRoute: AuthenticatedInsightsReceptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrackTokenRoute: TrackTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
